### ISSUE TITLE
Empty device name when can't find saved device

### ISSUE THREAD

**Issue by jbeomchoi** [Off-Live/myty-kit#20]
## Situation

- When building application with MYTY Kit
  - Selected camdevice is saved in the scene on GameObject containing `CameraSource`
    <img width="345" alt="image" src="https://user-images.githubusercontent.com/65939592/197951760-c5fe3d09-28d3-4e91-a25e-357200913664.png">
- Then, when application is started, there can be an error like below
  <img width="639" alt="image" src="https://user-images.githubusercontent.com/65939592/197952234-192efdb4-b0c8-4592-9a7d-6e119400fc07.png">

## Solution

- When saving scene, empty `camDeviceName` property manually
  - It can be prevented this way, but it seems better to update `CameraSource` code, assuming saved device name cannot be found in the current execution

**Comment by apsntian** [comment]
Very good support. Thanks a lot!

**Comment by apsntian** [comment]
I'll apply this in 1.0.0
