### ISSUE TITLE
Tracing? Tracking?

### ISSUE THREAD

**Issue by Hyunyoun** [Off-Live/myty-kit#34]
https://github.com/Off-Live/myty-kit/blob/c13810ec2057c10d19d5a4a500a97763e07c300e/Assets/MYTYKit/Scripts/MetaverseKit/AR/ARFaceTracing.cs#L6

maybe typo?

**Comment by jbeomchoi** [comment]
https://github.com/Off-Live/myty-kit/commit/92615e96707aa6540d6e9f95d690f96ca55f302b
Fixed on this commit
